CLASS zcl_travel_unittest_odatav2_ab DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zcl_travel_unittest_odatav2_ab  IMPLEMENTATION.
ENDCLASS.
